#!/bin/bash

# display splash screen as Openbox background
if [ -f /boot/firmware/splash.png ]; then
   feh --bg-center /boot/firmware/splash.png
fi

VNC_ENABLED=$(get-ini /boot/firmware/kioskbrowser.ini vnc enabled)
if [ "${VNC_ENABLED}" -eq 1 ]
then
	x11vnc -localhost &
fi

# move the cursor out of the way
xdotool mousemove 0 0

# disable blanking or configure user-defined blanking interval
BLANKING=$(get-ini /boot/firmware/kioskbrowser.ini screen blanking_interval)
if [ -n "${BLANKING}" ]
then
        xset s "${BLANKING}" # blank after n seconds
else
        xset s off # don't activate screensaver
        xset -dpms # disable DPMS (Energy Star) features.
        xset s noblank # don't blank the video device
fi

# hide mouse cursor after 1 second
unclutter -idle 1 -root &

# set a custom audio output device (if specified)
AUDIO_DEVICE=$(get-ini /boot/firmware/kioskbrowser.ini audio device)
if [ -n "${AUDIO_DEVICE}" ]
then
	echo "pcm.!default \"${AUDIO_DEVICE}\"" > /tmp/asoundrc
fi

# set a custom resolution (if specified)
RESOLUTION=$(get-ini /boot/firmware/kioskbrowser.ini screen force_resolution)
if [ -n "${RESOLUTION}" ]
then
	MONITOR=$(xrandr -q | grep " connected" | awk '{ print $1; }')
	xrandr --output "${MONITOR}" --mode "${RESOLUTION}"
fi

# set a custom modeline (if specified)
CUSTOM_MODELINE=$(get-ini /boot/firmware/kioskbrowser.ini screen custom_modeline)
if [ -n "${CUSTOM_MODELINE}" ]
then
	MONITOR=$(xrandr -q | grep " connected" | awk '{ print $1; }')
	xrandr --newmode "custom" ${CUSTOM_MODELINE}
	xrandr --addmode "${MONITOR}" "custom"
	xrandr --output "${MONITOR}" --mode "custom"
fi

# set a screen rotation (if specified)
ROTATE_SCREEN=$(get-ini /boot/firmware/kioskbrowser.ini screen rotate_screen)
if [ -n "${ROTATE_SCREEN}" ]
then
	MONITOR=$(xrandr -q | grep " connected" | awk '{ print $1; }')
	xrandr --output "${MONITOR}" --rotate ${ROTATE_SCREEN}	
fi

# enable/disable dark mode
DARK_MODE=$(get-ini /boot/firmware/kioskbrowser.ini browser darkmode)
if [ "${DARK_MODE}" -eq 1 ]
then
    export GTK_THEME=Adwaita-dark
    CHROME_DARK_MODE_FLAGS="--enable-features=WebContentsForceDark:inversion_method/cielab_based/image_behavior/none"
else
	export GTK_THEME=Adwaita
	CHROME_DARK_MODE_FLAGS=""
fi

# enable/disable hardware acceleration
HW_ACCEL=$(get-ini /boot/firmware/kioskbrowser.ini browser hardware_accel)
if [ "${HW_ACCEL}" -eq 1 ]
then
    CHROME_GPU_FLAGS=""
else
    CHROME_GPU_FLAGS="--disable-gpu"
fi

# enable/disable low_end_device_mode
LOW_END=$(get-ini /boot/firmware/kioskbrowser.ini browser low_end_device_mode)
if [ "${LOW_END}" -eq 1 ]
then
    CHROME_LOW_END_FLAGS="--enable-low-end-device-mode --disable-composited-antialiasing --disable-low-res-tiling"
else
    CHROME_LOW_END_FLAGS="--disable-low-end-device-mode"
fi

# enable/disable "disk" caching (ram disk in our case)
DISABLE_CACHE=$(get-ini /boot/firmware/kioskbrowser.ini browser disable_cache)
if [ "${DISABLE_CACHE}" -eq 1 ]
then
    CHROME_CACHE_FLAGS="--disk-cache-dir=/dev/null"
else
    CHROME_CACHE_FLAGS=""
fi

# start chromium
URL=$(get-ini /boot/firmware/kioskbrowser.ini browser url)
chromium --start-fullscreen \
		 --allow-insecure-localhost \
		 --autoplay-policy=no-user-gesture-required \
		 --check-for-update-interval=1 \
		 --disable-component-update \
		 --disable-features=Translate \
		 --disable-features=TranslateUI \
		 --disable-infobars \
		 --disable-pinch \
		 --disable-session-crashed-bubble \
		 --disable-smooth-scrolling \
		 --kiosk \
		 --noerrdialogs \
		 --overscroll-history-navigation=0 \
		 --simulate-critical-update \
		 --simulate-outdated-no-au='Tue, 31 Dec 2099 23:59:59 GMT' \
		 --touch-events=enabled \
		 --process-per-site \
		 --no-memcheck \
		 ${CHROME_DARK_MODE_FLAGS} \
		 ${CHROME_GPU_FLAGS} \
		 ${CHROME_LOW_END_FLAGS} \
		 ${CHROME_CACHE_FLAGS} \
		 ${URL} &

# if a cache clearing interval is specified, launch the cache-clear-timer (while true, sleep, rm -rf)
CACHE_CLEAR=$(get-ini /boot/firmware/kioskbrowser.ini browser cache_clear_interval)
if [ -n "${CACHE_CLEAR}" ]
then
	/usr/bin/cache-clear-timer "${CACHE_CLEAR}" &
fi
