name: CI

on:
  create: { }
  pull_request: { }

permissions:
  contents: write

jobs:
  x86:
    runs-on: [ubuntu-latest]

    outputs:
      pkgfile: ${{ steps.pkgname.outputs.pkgfile }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -yqq libguestfs-tools qemu-utils qemu-system-x86 ovmf qemu-block-extra qemu-user-static binfmt-support rsync sudo wget xz-utils pigz mount dosfstools libarchive-tools debootstrap zerofree util-linux
          
      - name: Build firmware
        run: |
          ./build_x86.sh

      - name: Release build artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          append_body: true
          body_path: ./version-info
          files: |
            ./anotterkiosk-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  raspberrypi:
    runs-on: [self-hosted, hetzner-cax21]

    outputs:
      pkgfile: ${{ steps.pkgname.outputs.pkgfile }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -yqq libguestfs-tools qemu-utils qemu-system-arm qemu-efi-aarch64 qemu-block-extra qemu-user-static binfmt-support rsync sudo wget xz-utils pigz mount dosfstools libarchive-tools zerofree util-linux
          
      - name: Build firmware
        run: |
          ./build_raspberry_pi.sh

      - name: Release build artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          append_body: true
          body_path: ./version-info
          files: |
            ./anotterkiosk-*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}